### ISSUE TITLE
請問如何安裝這個系統？

### ISSUE THREAD

**Issue by xinjiayu** [ggg44473/HKS#33]
請問有沒有安裝的說明文檔呢？

對於你們這個系統很感興趣，想安裝起來試用一下。下載回本地沒有運行起來，還請指點。謝謝！

**Comment by h20110213** [comment]
本系統採用Laravel 5.7，請確認您的本地環境PHP有7.2 (建議可用 Wamp.net )，並且執行過composer install、npm  install，建立db，還原.env、generate Key、mail key(Google)、pusher key(Pusher)，詳細安裝說明指令可以參考[Laravel clone](https://oomusou.io/laravel/laravel-clone-from-github/)或Google相關內容，如有問題歡迎再反映。 

實際佈署成功後如下所展示 :
[Goal Care](https://www.goalcare.ga/)
